autoservisas/urls.py
from django.views.generic import RedirectView
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paslaugos/', include('paslaugos.urls')),
    path('captcha/', include('captcha.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', RedirectView.as_view(url='paslaugos/', permanent=True))
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

paslaugos/urls.py
from django.urls import path, include
from .views import *





urlpatterns = [
    path('', index, name='index'),
    path('automobiliai/', automobiliai, name='automobiliai'),
    path('automobilio_modeliai/', automobilio_modeliai, name='automobilio_modeliai'),
    path('uzsakymai/', UzsakymaiListView.as_view(), name='uzsakymas'),
    path('uzsakymai/<int:pk>', UzsakymasDetailView.as_view(), name='uzsakymas-detail'),
    path('paslauga/', paslauga, name='paslauga'),
    path('automobilio_duomenys/<int:automobilis_id>/', automobilio_duomenys, name='automobiliu_duomenys'),
    path('saskaitos/', SaskaitosListView.as_view(), name='saskaitos'),
    path('saskaitos/<int:pk>', SaskaitosDetailView.as_view(), name='saskaitos-detail'),
    path('search/', search, name='search'),
    path('logout/', CustomLogout.as_view(), name='logout'),
    path('manoauto/', AutoByUserListView.as_view(), name='manoauto'),
    path('manoautomobiliai/new', UzsakymasByUserCreateView.as_view(), name='manoauto_new'),
    path('register/', register, name='register'),
    path('profilis/', profilis, name='profilis'),
    path('manoauto/<int:pk>/update', UzsakymasByUserUpdateView.as_view(), name='my-automobiliai-update'),
    path('manoauto/<int:pk>/delete', UzsakymasByUserDeleteView.as_view(), name='my-automobiliai-delete'),
    path('i18n/', include('django.conf.urls.i18n')),
    ]

paslaugos/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from datetime import date, datetime
import pytz
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _



class AutomobilioModelis(models.Model):
    marke = models.CharField(max_length=50)
    modelis = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Automobilio modelis'
        verbose_name_plural = 'Automobilio modeliai'
        db_table = 'automobilio modelis'

    def __str__(self):
        return f'{self.marke} {self.modelis}'


class Automobilis(models.Model):
    valstybinis_nr = models.CharField(max_length=20)
    automobilio_modelis = models.ForeignKey(AutomobilioModelis, on_delete=models.SET_NULL, null=True)
    vin_kodas = models.CharField(max_length=20, null=True)
    klientas = models.CharField(max_length=50, null=True)
    defektai = HTMLField()
    virselis = models.ImageField(upload_to='covers', null=True, blank=True)

    class Meta:
        verbose_name = 'Automobilis'
        verbose_name_plural = 'Automobiliai'
        db_table = 'automobilis'

    def __str__(self):
        return f'{self.klientas} : {self.automobilio_modelis} --> {self.valstybinis_nr}'


class Uzsakymas(models.Model):
    data = models.DateTimeField(auto_now=True)
    automobilis = models.ForeignKey(Automobilis, on_delete=models.CASCADE, null=True)
    suma = models.DecimalField(default=0, decimal_places=2, max_digits=8)
    vartotojas = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    atsiemimo_data = models.DateTimeField(null=True, blank=True)
    aprasymas = models.TextField('Problemos aprašymas', max_length=2000, default='', null=True, blank=True)


    @property
    def is_overdue(self):
        if self.atsiemimo_data and datetime.today().replace(tzinfo=pytz.utc) > self.atsiemimo_data.replace(tzinfo=pytz.utc):
            return True
        return False

    STATUSAS = (
        ('p', 'Priimtas'),
        ('v', 'Vykdomas'),
        ('i', 'Įvykdytas'),
        ('a', 'Apmokėtas'),
    )
    status = models.CharField('Užsakymo statusas',
                              max_length=1,
                              choices=STATUSAS,
                              blank=True,
                              default='s',
                              help_text='Pažymėti užsakymo statusą, pirminis - "Suformuotas"',
                              )



    class Meta:
        ordering = ['data']
        verbose_name = 'Uzsakymas'
        verbose_name_plural = 'Uzsakymai'
        db_table = 'uzsakymas'



    def __str__(self):
        return f"{self.data.strftime('%Y-%m-%d %H:%M')} - {self.automobilis} : {self.suma}"


class Paslauga(models.Model):
    pavadinimas = models.CharField(max_length=50, null=True)
    kaina = models.DecimalField(default=0, decimal_places=2, max_digits=8)
    aprasymas = HTMLField()

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'
        db_table = 'paslaugos'

    def __str__(self):
        return f'{self.pavadinimas} {self.aprasymas}'


class UzsakymoEilute(models.Model):
    paslauga = models.ForeignKey(Paslauga, on_delete=models.SET_NULL, null=True)
    uzsakymas = models.ForeignKey(Uzsakymas, on_delete=models.SET_NULL, null=True)
    kiekis = models.IntegerField(default=0)
    kaina = models.DecimalField(default=0, decimal_places=2, max_digits=8)


    class Meta:
        verbose_name = 'Uzsakymo eilute'
        verbose_name_plural = 'Uzsakymo eilutes'
        db_table = 'uzsakymo eilutes'

    def __str__(self):
        return f'{self.paslauga} - {self.uzsakymas} - {self.kaina}'

    def save(self, *args, **kwargs):
        self.kaina = self.kiekis * self.paslauga.kaina
        super().save(*args, **kwargs)
        uzsakymas = self.uzsakymas
        uzsakymas.suma = uzsakymas.uzsakymoeilute_set.all().aggregate(Sum('kaina'))['kaina__sum'] or 0
        uzsakymas.save()


class UzsakymasReview(models.Model):
    uzsakymas = models.ForeignKey('Uzsakymas', on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Atsiliepimas', max_length=2000)

    class Meta:
        verbose_name = "Atsiliepimas"
        verbose_name_plural = 'Atsiliepimai'
        ordering = ['-date_created']

class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="profile_pics/default.jpg", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300 or img.height < 150 or img.width < 150:
            output_size = (150, 150)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

paslaugos/forms.py
from django.shortcuts import render

from .models import *
from django import forms
from captcha.fields import CaptchaField
from django.contrib.auth.models import User

class UzsakymasReviewForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = UzsakymasReview
        fields = ('content', 'uzsakymas', 'reviewer', 'captcha')
        widgets = {'uzsakymas': forms.HiddenInput(), 'reviewer': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

class UserAutomobilisCreateForm(forms.ModelForm):

    class Meta:
        model = Uzsakymas
        fields = ['vartotojas', 'automobilis', 'atsiemimo_data']
        widgets = {'vartotojas': forms.HiddenInput, 'atsiemimo_data': forms.DateTimeInput(format=('%Y-%m-%dT%H:%M'), attrs={'type': 'datetime-local'})}

paslaugos/views.py
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import *
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from .forms import UzsakymasReviewForm, UserAutomobilisCreateForm
from django.contrib.auth.decorators import login_required
from .forms import UzsakymasReviewForm, UserUpdateForm, ProfilisUpdateForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.translation import gettext as _


def index(request):
    num_modelis = AutomobilioModelis.objects.all().count()
    num_automobilis = Automobilis.objects.all().count()
    num_uzsakymas = Uzsakymas.objects.all().count()
    num_paslauga = Paslauga.objects.all()
    num_eilute = UzsakymoEilute.objects.all().count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_modelis': num_modelis,
        'num_automobilis': num_automobilis,
        'num_uzsakymas': num_uzsakymas,
        'num_paslauga': num_paslauga,
        'num_eilute': num_eilute,
        'num_visits': num_visits,

    }
    return render(request, 'paslaugos/index.html', context=context)


def automobiliai(request):
    automobiliai = Automobilis.objects.all()
    return render(request, 'paslaugos/automobiliai.html', {'automobiliai': automobiliai})


def automobilio_modeliai(request):
    paginator = Paginator(AutomobilioModelis.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_auto = paginator.get_page(page_number)
    return render(request, 'paslaugos/automobiliomodelis.html', {'automobilio_modeliai': paged_auto})


class UzsakymaiListView(generic.ListView):
    model = Uzsakymas
    paginate_by = 2
    template_name = 'paslaugos/uzsakymas.html'


class UzsakymasDetailView(FormMixin, generic.DetailView):
    model = Uzsakymas
    template_name = 'paslaugos/uzsakymas_detail.html'
    form_class = UzsakymasReviewForm

    def get_success_url(self):
        return reverse('uzsakymas-detail', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.uzsakymas = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(UzsakymasDetailView, self).form_valid(form)


def paslauga(request):
    paslauga = Paslauga.objects.all()
    return render(request, 'paslaugos/paslauga.html', {'paslauga': paslauga})


def automobilio_duomenys(request, automobilis_id):
    automobilio_modelis = get_object_or_404(Automobilis, pk=automobilis_id)
    return render(request, 'paslaugos/automobilio_duomenys.html', {'automobilio_duomenys': automobilio_modelis})


class SaskaitosListView(generic.ListView):
    model = Uzsakymas
    template_name = 'paslaugos/saskaitos_list.html'


class SaskaitosDetailView(generic.DetailView):
    model = Uzsakymas
    template_name = 'paslaugos/saskaitos_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SaskaitosDetailView, self).get_context_data(**kwargs)
        context['uzsakymo_eilutes'] = UzsakymoEilute.objects.all()
        return context


def search(request):
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(Q(klientas__icontains=query)
                                                | Q(automobilio_modelis__modelis__icontains=query)
                                                | Q(automobilio_modelis__marke__icontains=query)
                                                | Q(valstybinis_nr__icontains=query)
                                                | Q(vin_kodas__icontains=query))
    return render(request, 'paslaugos/search.html', {'automobilis': search_results, 'query': query})


class CustomLogout(LogoutView):
    template_name = 'registration/logged_out.html'


class AutoByUserListView(LoginRequiredMixin, generic.ListView):
    model = Uzsakymas
    template_name = 'paslaugos/vartotojo_auto.html'
    paginate_by = 10

    def get_queryset(self):
        return Uzsakymas.objects.filter(vartotojas=self.request.user).order_by('atsiemimo_data')


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _(f'Username %s already exists') % username)
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _(f'Email %s already exists') % email)
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'paslaugos/register.html')


@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'paslaugos/profilis.html', context)


class UzsakymasByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzsakymas
    # fields = ['book', 'due_back']
    success_url = "/paslaugos/manoauto/"
    template_name = 'paslaugos/user_automobilis_form.html'
    form_class = UserAutomobilisCreateForm

    def form_valid(self, form):
        form.instance.reader = self.request.user
        return super().form_valid(form)


class UzsakymasByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Uzsakymas
    fields = ['automobilis', 'grazinimo_data']
    success_url = "/paslaugos/manoauto/"
    template_name = 'paslaugos/user_automobilis_form.html'

    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        return super().form_valid(form)

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.vartotojas


class UzsakymasByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Uzsakymas
    success_url = "/paslaugos/manoauto/"
    template_name = 'paslaugos/user_uzsakymas_delete.html'

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.vartotojas

paslaugos/templates/paslaugos/automobiliai.html
{% extends "paslaugos/base.html" %}

{% block content %}

<p>{{ defektai | safe }}</p>
{% load static %}
    <h1>Automobiliai : </h1></br>
    {% if automobiliai %}
    <div class="row">
      {% for auto in automobiliai %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if auto.virselis %}
              <img src="{{ auto.virselis.url }}" width="200" height="150" class="card-img-top" alt="...">
            {% else %}
              <iframe width="150" height="150" src="https://www.youtube.com/embed/cKp7IEDK28c"
                      frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">< {{ auto.automobilio_modelis }}> {{auto.valstybinis_nr}}</h6>
              <p class="card-text"><a href="{{ book.id }}">{{ auto.klientas }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>Automobiliu nėra.</p>
    {% endif %}

  <h1>Automobiliai</h1>
  <p>Klientu sąrašas :</p>
  {% for a in automobiliai %}
    <li>{{a.klientas}} : {{a.valstybinis_nr}}  {{a.vin_kodas}} </li>
    {% endfor %}
{% endblock %}

paslaugos/templates/paslaugos/automobilio_duomenys.html
{% extends "paslaugos/base.html" %}


{% block content %}
    <div>
    <h4>{{ automobilio_duomenys }}</h4>
        <p>{{ automobilio_duomenys.defektai | safe | truncatechars_html:200 }}</p>
    <br>
        <h5>Rodoma detali informacija apie kliento - {{ automobilio_duomenys.klientas }} - automobilį:</h5>
            <ul>
                <li>Valstybinis numeris: {{ automobilio_duomenys.valstybinis_nr }}</li>
                <li>Automobilio modelis: {{ automobilio_duomenys.automobilio_modelis }}</li>
                <li>VIN numeris: {{ automobilio_duomenys.vin_kodas }}</li>
            </ul>
    </div>
{% endblock %}

paslaugos/templates/paslaugos/automobiliomodelis.html
{% extends "paslaugos/base.html" %}

{% block content %}
{% load static %}
    <h1>Klientai :</h1></br>
    {% if automobilio_modeliai %}
    <div class="row">
      {% for auto in automobilio_modeliai %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if auto.automobiliomodelis.automobilis.virselis %}
              <img src="{{ auto.virselis.url }}" width="200" height="150" class="card-img-top" alt="...">
            {% else %}
              <iframe width="150" height="150" src="https://www.youtube.com/embed/VTDB3mKx7jM"
                      frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ auto.modelis }}</h6>
              <p class="card-text"><a href="{{ book.id }}">{{ auto.marke }}</a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>Automobiliu nėra.</p>
    {% endif %}
  <h1>Automobiliu modeliai :</h1>
  {% for a in automobilio_modeliai %}
    <li><a href="{% url 'automobiliu_duomenys' a.id %}">{{a.marke}} - {{a.modelis}}</a> </li>
    {% endfor %}
<br>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if automobilio_modeliai.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in automobilio_modeliai.paginator.page_range %}
                    {% if automobilio_modeliai.number == i %}
                        <li class="page-item active">
                            <a class="page-link">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>

{% endblock %}

paslaugos/templates/paslaugos/index.html
{% extends "paslaugos/base.html" %}
{% block content %}
{% load i18n %}
<p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
  <h3>{% trans "Carservice" %}</h3>
  <p><b>Meniu:</b></p>
  <ul>
    <li><strong>{% trans "Services " %}:</strong>
      {% for i in num_paslauga %}
      {{ i.pavadinimas }},</li>
    {% endfor %}
    <li><strong>{% trans "Number of customers" %}:</strong> {{ num_uzsakymas }}</li>
    <li><strong>{% trans "Number of models" %}:</strong> {{ num_modelis }}</li>
    <li><strong>{% trans "Number of cars" %}:</strong> {{ num_automobilis }}</li>
    <li><strong>{% trans "Quantity of orders" %}:</strong> {{ num_eilute }}</li>
  </ul>


{% endblock %}

paslaugos/templates/paslaugos/profilis.html
{% extends "paslaugos/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

paslaugos/templates/paslaugos/saskaitos_detail.html
{% extends "paslaugos/base.html" %}
{% block content %}
  <h5>Uzsakymo numeris: {{ uzsakymas.id }}</h5>
    <br>
    <p><strong>Klientas:</strong> {{ uzsakymas.automobilis }}</p>
    <p><strong>Užsakymo data:</strong> {{ uzsakymas.data }}</p>
    <p><strong>Sąskaitos suma:</strong> {{ uzsakymas.suma }}</p>
    <p><strong>Suteiktos paslaugos:</strong> </p>
    <ul>
          {% for s in uzsakymo_eilutes %}
            {% if s.uzsakymas_id == uzsakymas.id %}
              <li>{{ s.uzsakymas.data }} - {{s.uzsakymas.automobilis}} - kiekis: {{ s.kiekis }} vnt. - kaina: {{ s.kaina }}</li>
            {% endif %}
          {% endfor %}
    </ul>

    <div style="margin-left:20px;margin-top:20px">
    <h6>Užsakymo statusas:</h6>
        <p class="{% if uzsakymas.statusas == 'p' %}text-success{% elif uzsakymas.statusas == 'i' %}text-danger{% else %}text-warning{% endif %}">
         {{ uzsakymas.get_status_display }}</p>
    </div>
{% endblock %}

paslaugos/templates/paslaugos/saskaitos_list.html
{% extends "paslaugos/base.html" %}
{% block content %}
  <h1>Sąskaitų sąrašas :</h1>
  {% if uzsakymas_list %}
  <ul>
    {% for s in uzsakymas_list %}
      <li>
        <a href="{{ s.id }}">{{ s.automobilis }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Sąskaitų nėra !!!</p>
  {% endif %}
{% endblock %}

paslaugos/templates/paslaugos/search.html
{% extends "paslaugos/base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if automobilis %}
  <ul>
    {% for a in automobilis %}
      <li>
        <a href="{{ a.id }}">{{ a.klientas }}</a> ({{a.automobilio_modelis}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

paslaugos/templates/paslaugos/user_automobiliai.html
{% extends "paslaugos/base.html" %}

{% block content %}
    <h1>Mano uzsakymai:</h1>
    <hr>
        <ul>
        <img class="rounded-circle" src="{{object.vartotojas.profilis.nuotrauka.url}}">
        <li><strong class="{% if object.atsiemimo_data %}text-danger{% endif %}">Pavadinimas: {{object.automobilis}}</strong></li>
        <li><strong>Gražinimo terminas:</strong> {{object.atsiemimo_data}}</li>
            {% if object.vartotojas == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'my-automobiliai-update' object.id %}">Redaguoti</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'my-automobiliai-delete' object.id %}">Ištrinti</a>
            </div>
            {% endif %}
        <br/>
      </li>
    </ul>
{% endblock %}

paslaugos/templates/paslaugos/uzsakymas.html
{% extends "paslaugos/base.html" %}

{% block content %}

  <h1>Uzsakymai :</h1>
  <ul>
    {% for uzsakymas in uzsakymas_list %}
      <li>
        <a href="{{ uzsakymas.id }}">{{ uzsakymas.id }} | {{ uzsakymas.data }} >>> {{ uzsakymas.automobilis }}</a>
      </li>
    {% endfor %}
  </ul>
<br>
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>

</div>
     </br>
{% endblock %}

paslaugos/templates/paslaugos/vartotojo_auto.html
{% extends "paslaugos/base.html" %}

{% block content %}

<ul>
    {% if uzsakymas_list %}
    <h1>Mano "{{ uzsakymas_list.0.vartotojas }}" uzsakymai: </h1>
    <img class="rounded-circle" src="{{uzsakymas_list.0.vartotojas.profilis.nuotrauka.url}}" style="width:50px; height:50px;">
    <iframe src="https://giphy.com/embed/oXKxyPM7oTIMYz4RJi" width="200" height="200" frameBorder="0" class="giphy-embed" allowFullScreen>

    </iframe>
    <p><a href="https://giphy.com/gifs/creative-courage-funny-kids-child-checks-cashed-drifting-kid-oXKxyPM7oTIMYz4RJi"></a>
    </p>
      {% for u in uzsakymas_list %}
      <li class="{% if u.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'automobiliu_duomenys' u.automobilis_id %}">{{u.automobilio_modelis.modelis}}({{ u.atsiemimo_data }})</a>
            </li>
      {% endfor %}
    </ul>


    {% else %}
      <p>Šiuo metu nera automobiliu.</p>
    {% endif %}       
{% endblock %}